// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (name,email,password_hash) VALUES ($1,$2,$3)
RETURNING id, name, email, created_at, password_hash
`

type CreateAuthorParams struct {
	Name         string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, createAuthor, arg.Name, arg.Email, arg.PasswordHash)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getAuthorByEmail = `-- name: GetAuthorByEmail :one
SELECT id, name, email, created_at, password_hash FROM authors
WHERE email=$1
`

func (q *Queries) GetAuthorByEmail(ctx context.Context, email string) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthorByEmail, email)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getAuthorById = `-- name: GetAuthorById :one
SELECT id, name, email, created_at, password_hash FROM authors
WHERE id = $1
`

func (q *Queries) GetAuthorById(ctx context.Context, id pgtype.UUID) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthorById, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getAuthorByName = `-- name: GetAuthorByName :one
SELECT id, name, email, created_at, password_hash FROM authors
WHERE LOWER(name) = LOWER($1)
`

func (q *Queries) GetAuthorByName(ctx context.Context, lower string) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthorByName, lower)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}
