// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blogs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBlog = `-- name: CreateBlog :one
INSERT INTO blogs (author_id, title, slug, body)
VALUES ($1, $2, $3, $4)
RETURNING id, author_id, title, slug, body, created_at, updated_at
`

type CreateBlogParams struct {
	AuthorID pgtype.UUID
	Title    string
	Slug     string
	Body     string
}

func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error) {
	row := q.db.QueryRow(ctx, createBlog,
		arg.AuthorID,
		arg.Title,
		arg.Slug,
		arg.Body,
	)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBlogBySlug = `-- name: GetBlogBySlug :one
SELECT 
    b.id, b.title, b.slug, b.body, b.created_at, b.updated_at,
    a.id AS author_id, a.name AS author_name, a.email AS author_email
FROM blogs b
JOIN authors a ON a.id = b.author_id
WHERE b.slug = $1 LIMIT 1
`

type GetBlogBySlugRow struct {
	ID          pgtype.UUID
	Title       string
	Slug        string
	Body        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	AuthorID    pgtype.UUID
	AuthorName  string
	AuthorEmail string
}

func (q *Queries) GetBlogBySlug(ctx context.Context, slug string) (GetBlogBySlugRow, error) {
	row := q.db.QueryRow(ctx, getBlogBySlug, slug)
	var i GetBlogBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.AuthorName,
		&i.AuthorEmail,
	)
	return i, err
}

const listBlogs = `-- name: ListBlogs :many
SELECT 
    b.id, b.title, b.slug, b.body, b.created_at,
    a.name AS author_name
FROM blogs b
JOIN authors a ON a.id = b.author_id
ORDER BY b.created_at DESC
LIMIT $1 OFFSET $2
`

type ListBlogsParams struct {
	Limit  int32
	Offset int32
}

type ListBlogsRow struct {
	ID         pgtype.UUID
	Title      string
	Slug       string
	Body       string
	CreatedAt  pgtype.Timestamptz
	AuthorName string
}

func (q *Queries) ListBlogs(ctx context.Context, arg ListBlogsParams) ([]ListBlogsRow, error) {
	rows, err := q.db.Query(ctx, listBlogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlogsRow
	for rows.Next() {
		var i ListBlogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlogById = `-- name: UpdateBlogById :one
UPDATE blogs
SET 
    title      = COALESCE($2, title),
    body       = COALESCE($3, body),
    updated_at = NOW()
WHERE id = $1
RETURNING id, author_id, title, slug, body, created_at, updated_at
`

type UpdateBlogByIdParams struct {
	ID    pgtype.UUID
	Title pgtype.Text
	Body  pgtype.Text
}

func (q *Queries) UpdateBlogById(ctx context.Context, arg UpdateBlogByIdParams) (Blog, error) {
	row := q.db.QueryRow(ctx, updateBlogById, arg.ID, arg.Title, arg.Body)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
