// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: likes_comments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLikes = `-- name: CountLikes :one
SELECT COUNT(*)::bigint FROM blog_likes
WHERE blog_id = $1
`

func (q *Queries) CountLikes(ctx context.Context, blogID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLikes, blogID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO blog_comments (blog_id, author_id, parent_id, content)
VALUES ($1, $2, $3, $4)
RETURNING id, blog_id, author_id, parent_id, content, created_at, updated_at
`

type CreateCommentParams struct {
	BlogID   pgtype.UUID
	AuthorID pgtype.UUID
	ParentID pgtype.UUID
	Content  string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (BlogComment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.BlogID,
		arg.AuthorID,
		arg.ParentID,
		arg.Content,
	)
	var i BlogComment
	err := row.Scan(
		&i.ID,
		&i.BlogID,
		&i.AuthorID,
		&i.ParentID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM blog_comments
WHERE id = $1 AND author_id = $2
`

type DeleteCommentParams struct {
	ID       pgtype.UUID
	AuthorID pgtype.UUID
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) error {
	_, err := q.db.Exec(ctx, deleteComment, arg.ID, arg.AuthorID)
	return err
}

const deleteLike = `-- name: DeleteLike :exec
DELETE FROM blog_likes
WHERE blog_id = $1 AND author_id = $2
`

type DeleteLikeParams struct {
	BlogID   pgtype.UUID
	AuthorID pgtype.UUID
}

func (q *Queries) DeleteLike(ctx context.Context, arg DeleteLikeParams) error {
	_, err := q.db.Exec(ctx, deleteLike, arg.BlogID, arg.AuthorID)
	return err
}

const getLikeByUser = `-- name: GetLikeByUser :one
SELECT id FROM blog_likes
WHERE blog_id = $1 AND author_id = $2
LIMIT 1
`

type GetLikeByUserParams struct {
	BlogID   pgtype.UUID
	AuthorID pgtype.UUID
}

func (q *Queries) GetLikeByUser(ctx context.Context, arg GetLikeByUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getLikeByUser, arg.BlogID, arg.AuthorID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertLike = `-- name: InsertLike :exec
INSERT INTO blog_likes (blog_id, author_id)
VALUES ($1, $2)
ON CONFLICT (blog_id, author_id) DO NOTHING
`

type InsertLikeParams struct {
	BlogID   pgtype.UUID
	AuthorID pgtype.UUID
}

func (q *Queries) InsertLike(ctx context.Context, arg InsertLikeParams) error {
	_, err := q.db.Exec(ctx, insertLike, arg.BlogID, arg.AuthorID)
	return err
}

const listCommentsByBlogId = `-- name: ListCommentsByBlogId :many
SELECT 
    c.id, c.blog_id, c.author_id, c.parent_id, c.content, c.created_at, c.updated_at,
    a.name AS author_name, a.avatar_url AS author_avatar_url
FROM blog_comments c
JOIN authors a ON a.id = c.author_id
WHERE c.blog_id = $1
ORDER BY c.created_at ASC
`

type ListCommentsByBlogIdRow struct {
	ID              pgtype.UUID
	BlogID          pgtype.UUID
	AuthorID        pgtype.UUID
	ParentID        pgtype.UUID
	Content         string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	AuthorName      string
	AuthorAvatarUrl string
}

func (q *Queries) ListCommentsByBlogId(ctx context.Context, blogID pgtype.UUID) ([]ListCommentsByBlogIdRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByBlogId, blogID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsByBlogIdRow
	for rows.Next() {
		var i ListCommentsByBlogIdRow
		if err := rows.Scan(
			&i.ID,
			&i.BlogID,
			&i.AuthorID,
			&i.ParentID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.AuthorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
