// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMediaUpload = `-- name: CreateMediaUpload :one
INSERT INTO media_uploads (id, filename, content_type, byte_size, data)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, filename, content_type, byte_size, created_at
`

type CreateMediaUploadParams struct {
	ID          pgtype.UUID
	Filename    string
	ContentType string
	ByteSize    int32
	Data        []byte
}

type CreateMediaUploadRow struct {
	ID          pgtype.UUID
	Filename    string
	ContentType string
	ByteSize    int32
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateMediaUpload(ctx context.Context, arg CreateMediaUploadParams) (CreateMediaUploadRow, error) {
	row := q.db.QueryRow(ctx, createMediaUpload,
		arg.ID,
		arg.Filename,
		arg.ContentType,
		arg.ByteSize,
		arg.Data,
	)
	var i CreateMediaUploadRow
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.ContentType,
		&i.ByteSize,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaUploadById = `-- name: GetMediaUploadById :one
SELECT id, filename, content_type, byte_size, data, created_at
FROM media_uploads
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMediaUploadById(ctx context.Context, id pgtype.UUID) (MediaUpload, error) {
	row := q.db.QueryRow(ctx, getMediaUploadById, id)
	var i MediaUpload
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.ContentType,
		&i.ByteSize,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}
