// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID           pgtype.UUID
	Name         string
	Email        string
	CreatedAt    pgtype.Timestamptz
	PasswordHash pgtype.Text
	GoogleID     pgtype.Text
	AvatarUrl    string
}

type Blog struct {
	ID          pgtype.UUID
	AuthorID    pgtype.UUID
	Title       string
	Slug        string
	Body        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	BannerImage string
	Tags        []string
}

type BlogComment struct {
	ID        pgtype.UUID
	BlogID    pgtype.UUID
	AuthorID  pgtype.UUID
	ParentID  pgtype.UUID
	Content   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type BlogLike struct {
	ID        pgtype.UUID
	BlogID    pgtype.UUID
	AuthorID  pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type NewsletterSubscriber struct {
	ID        pgtype.UUID
	Email     string
	CreatedAt pgtype.Timestamptz
}
