// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: newsletter.sql

package db

import (
	"context"
)

const listNewsletterSubscribers = `-- name: ListNewsletterSubscribers :many
SELECT id, email, created_at FROM newsletter_subscribers
ORDER BY created_at DESC
`

func (q *Queries) ListNewsletterSubscribers(ctx context.Context) ([]NewsletterSubscriber, error) {
	rows, err := q.db.Query(ctx, listNewsletterSubscribers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NewsletterSubscriber
	for rows.Next() {
		var i NewsletterSubscriber
		if err := rows.Scan(&i.ID, &i.Email, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscribeNewsletter = `-- name: SubscribeNewsletter :one
INSERT INTO newsletter_subscribers (email)
VALUES ($1)
ON CONFLICT (email) DO UPDATE
SET email = EXCLUDED.email
RETURNING id, email, created_at
`

func (q *Queries) SubscribeNewsletter(ctx context.Context, email string) (NewsletterSubscriber, error) {
	row := q.db.QueryRow(ctx, subscribeNewsletter, email)
	var i NewsletterSubscriber
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}
